### ISSUE TITLE
Not working on Sublime Text 3

### ISSUE THREAD

**Issue by ghost** [odyssomay/sublime-lispindent#12]
When I press a keybinding, nothing happens. Has anyone tested on ST3?

**Comment by odyssomay** [comment]
Nope, I don't have access to version 3, and I don't have enough money to buy it right now. :(

You can press _ctrl+`_ and see if you spot any errors.

**Comment by odyssomay** [comment]
I looked at the [porting guide](http://www.sublimetext.com/docs/3/porting_guide.html) but couldn't really find anything that should break.

**Comment by odyssomay** [comment]
I just realised the manual install package is very outdated. Did you use that or did you use the package manager?

**Comment by bluemont** [comment]
I used Package Control.

Here is the console log:

```
reloading plugin lispindent.commands
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 72, in reload_plugin
    m = importlib.import_module(modulename)
  File "X/importlib/__init__.py", line 88, in import_module
  File "<frozen importlib._bootstrap>", line 1577, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1558, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1525, in _find_and_load_unlocked
  File "/Users/david/Library/Application Support/Sublime Text 3/Installed Packages/lispindent.sublime-package/commands.py", line 3, in <module>
ImportError: No module named 'indent'
```

**Comment by odyssomay** [comment]
I'm not entirely sure that will fix it, please try again and see if there is any errors.

**Comment by odyssomay** [comment]
Actually I'm pretty sure it wont, but try it anyway.

**Comment by bluemont** [comment]
I uninstalled and reinstalled via Package Control.

I get this error when pressing `enter` in a Clojure file:

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 531, in run_
    return self.run(edit)
  File "/Users/david/Library/Application Support/Sublime Text 3/Installed Packages/lispindent.sublime-package/commands.py", line 124, in run
  File "/Users/david/Library/Application Support/Sublime Text 3/Installed Packages/lispindent.sublime-package/commands.py", line 34, in insert_newline_and_indent
NameError: global name 'indent' is not defined
```

**Comment by odyssomay** [comment]
It's not necessary to reinstall. Package Control automatically upgrades the packages when starting sublime. You can also upgrade manually by pressing _ctrl+shift+p_ then selecting _Package Control: Upgrade package_.

Edit: or selecting _Package Control: Upgrade/Overwrite All Packages_

**Comment by odyssomay** [comment]
Did you try it with the new patch?

**Comment by bluemont** [comment]
I did; it appears to be working. Thank you!

**Comment by odyssomay** [comment]
That's good to hear! :)
Thanks for taking your time testing and reporting the results. :thumbsup: 

Closing.
