### ISSUE TITLE
AttributeError by start

### ISSUE THREAD

**Issue by s-trooper** [odyssomay/sublime-lispindent#2]
Hi, i am on win7. While Startup your plugin cause AttributeError

Traceback (most recent call last):
  File ".\sublime_plugin.py", line 205, in on_activated
  File ".\sublime_plugin.py", line 154, in run_timed_function
  File ".\sublime_plugin.py", line 204, in <lambda>
  File ".\commands.py", line 116, in on_activated
  File ".\commands.py", line 90, in init_env
  File ".\commands.py", line 66, in test_current_view
AttributeError: 'NoneType' object has no attribute 'active_view'

**Comment by odyssomay** [comment]
Which version of sublime are you using?

Also, how did you install the lispindent plugin?

**Comment by s-trooper** [comment]
Win7 x64

ST2 2.0.1 Build 2217
installed with Package Control -> Install Package

**Comment by odyssomay** [comment]
Woops, I get this error as well. :)

Sublime probably starts the plugin before it starts the window. It shouldn't affect the plugin's operation though. Are you able to use it?

**Comment by odyssomay** [comment]
Should be fixed now. :)

Thanks for reporting!
