### ISSUE TITLE
ImportError: No module named 'lispindent' in Sublime Text 3

### ISSUE THREAD

**Issue by ivan** [odyssomay/sublime-lispindent#25]
The keyboard shortcut wasn't working in Sublime Text 3 (3062), and I noticed this in the console:

```
reloading plugin sublime-lispindent.commands
Traceback (most recent call last):
  File "C:\SecuredPrograms\SublimeText\Data\Packages\sublime-lispindent\commands.py", line 4, in <module>
    import indent
ImportError: No module named 'indent'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\SecuredPrograms\SublimeText\sublime_plugin.py", line 71, in reload_plugin
    m = imp.reload(m)
  File "./imp.py", line 276, in reload
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "C:\SecuredPrograms\SublimeText\Data\Packages\sublime-lispindent\commands.py", line 6, in <module>
    from lispindent import indent
ImportError: No module named 'lispindent'
```

It worked fine when I changed `from lispindent import indent` to `from . import indent`

Related to #12; not sure why it worked before.

**Comment by odyssomay** [comment]
Sorry for taking so long to reply.

The reason it doesn't work is that the plugin directory is called _sublime-lispindent_ and not _lispindent_. Did you use [package control](https://sublime.wbond.net/) to install it?

I really like your suggestion `from . import indent` so I think I'll switch to that.

**Comment by ivan** [comment]
Nope, I wasn't using Package Control; I just copied it in.

**Comment by odyssomay** [comment]
Hopefully it works now. Thanks for submitting this issue! :+1:
